[book]
title = "UCollab Docs"
authors = ["Zachary Thomas"]
description = "This site provides all of the documentation currently available for UCollab."
language = "en"
multilingual = false
src = "docs/src"

[build]
build-dir = "docs/book"