services:
  mysql:
    container_name: ucollab-mysql
    image: mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: dev-password
      MYSQL_DATABASE: ucollab
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
