services:
  mysql:
    container_name: ucollab-mysql
    image: mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    container_name: ucollab-minio
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

  createbuckets:
    container_name: ucollab-createbuckets
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/ucollab;
      /usr/bin/mc anonymous set public myminio/ucollab;
      exit 0;
      "

  redis:
    container_name: ucollab-redis
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass "redis-password"
    volumes:
      - redis_data:/data

  redis-commander:
    container_name: ucollab-redis-commander
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379:0:redis-password
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  mysql_data:
  redis_data:
  minio_data:
