name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*  # Specify the Node.js version, or use a specific version like '16' if needed

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build  # Ensure the project is built before starting the server

    - name: Start server
      run: npm start &
      env:
        PORT: 3000  # Set the PORT environment variable if your app needs it

    - name: Wait for server to be ready
      run: npx wait-on http://localhost:3000

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
